### ISSUE TITLE
Error When Separation ToDoForm Component

### ISSUE THREAD

**Issue by dfoxster** [dfoxster/ToDo-List#1]
After separating the TodoForm into its own React component file, receive the following error:

Uncaught TypeError: addTodo is not a function
    at handleSubmit (<anonymous>:24:5)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4151:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4200:18)
    at invokeGuardedCallback (react-dom.development.js:4264:33)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4278:27)
    at executeDispatch (react-dom.development.js:9051:5)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9083:9)
    at processDispatchQueue (react-dom.development.js:9096:7)
    at dispatchEventsForPlugins (react-dom.development.js:9107:5)
    at react-dom.development.js:9298:14

**Comment by dfoxster** [comment]
Instead of TodoForm(addTodo) had to destructure props in the argument like this: TodoForm({ addTodo }).  Problem resolved.
